version: 0.0
Resources:
  - myEcsService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "VidTask"
        LoadBalancerInfo:
          ContainerName: "youtube"
          ContainerPort: 4000