apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-persistent-storage
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.PersistentStorage.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.PersistentStorage.storageClass | quote }}