apiVersion: v1
kind: Service
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  type: LoadBalancer
  selector:
    app: youtube
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
        - name: youtube
          image: ghcr.io/ddung1203/youtube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: youtube-persistent-storage
              mountPath: /app/uploads
          envFrom:
            - secretRef:
                name: mydata
          resources:
            requests:
              cpu: "0.5"
              memory: "1G"
            limits:
              cpu: "0.5"
              memory: "1G"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["cat", "/app/uploads/readiness/ready"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: youtube-persistent-storage
          persistentVolumeClaim:
            claimName: youtube-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: "nfs-client"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: youtube-hpa
spec:
  minReplcias: 3
  maxReplicas: 5
  targerCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: youtube
