apiVersion: v1
kind: Service
metadata:
  name: youtube
spec:
  type: LoadBalancer
  selector:
    app: youtube
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
        - name: youtube
          image: ddung1203/youtube:1
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: youtube-persistent-storage
              mountPath: /app/uploads
          envFrom:
          - secretRef:
              name: mydata
      volumes:
      - name: youtube-persistent-storage
        persistentVolumeClaim:
          claimName: youtube-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: 'nfs-client'