apiVersion: v1
kind: Secret
metadata:
  name: mydata
type: Opaque
data:
  MONGO_USERNAME: bW9uZ28K
  MONGO_PASSWORD: bW9uZ28K
  MONGO_URL: bW9uZ28ubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWwK
  COOKIE_SECRET: c2RlZ3Jma2Vmdzh0NjczMnJidWd3ZHFhdDgK
